apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: gitops-project

  source:
    repoURL: https://github.com/your-username/gitops-autoscaling-platform
    targetRevision: main
    path: infrastructure

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
